### ISSUE TITLE
md5 and sha256 files are wrong on testbuilds

### ISSUE THREAD

**Issue by hhl** [siduction/release-orga#20]
We are linking our builds.date.iso to builds.latest.iso on testbuilds, also the md5 and sha256 files which is wrong, the md5/sha256 file is generated against builds.date.iso and then only linked to the new file, that doesn't work and is totally wrong! 
We must generate a new builds.latest.iso.md5/sha256 file and copy this too testbuilds.

**Comment by fethomm** [comment]
Good catch.

**Comment by ak-li** [comment]
In my opinion the checksums in the md5/sha256 files are correct. The given filename contains the build date instead of 'latest' and at the same time the relase number is missing. If the iso file is renamed, the checksum test is successful.
For example:
```
$ mv siduction-Masters_of_War-xfce-amd64-latest.iso siduction-22.1.2-Masters_of_War-xfce-amd64-202305281611.iso
$ sha256sum -c siduction-Masters_of_War-xfce-amd64-latest.iso.sha256
siduction-22.1.2-Masters_of_War-xfce-amd64-202305281611.iso: OK
```
At the same time please eliminate the md5 files. They have been considered insecure for a long time.

**Comment by towo2099** [comment]
Ich habe keine ahnung, wie pyfll das macht.

**Comment by towo2099** [comment]
So, ich habe jetzt die Latest-Files komplett aus pyfll geschmissen.
